### ISSUE TITLE
URIError: Failed to decode param '%web_protocol%://192.168.1.168:%web_port%/webui/'

### ISSUE THREAD

**Issue by ice987987** [iobroker-community-adapters/ioBroker.webui#213]
after installation I get the following error:

`
URIError: Failed to decode param '%web_protocol%://192.168.1.168:%web_port%/webui/'
    at decodeURIComponent (<anonymous>)
    at decode_param (/opt/iobroker/node_modules/express/lib/router/layer.js:172:12)
    at Layer.match (/opt/iobroker/node_modules/express/lib/router/layer.js:148:15)
    at matchLayer (/opt/iobroker/node_modules/express/lib/router/index.js:585:18)
    at next (/opt/iobroker/node_modules/express/lib/router/index.js:226:15)
    at compression (/opt/iobroker/node_modules/compression/index.js:220:5)
    at Layer.handle [as handle_request] (/opt/iobroker/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/iobroker/node_modules/express/lib/router/index.js:328:13)
    at /opt/iobroker/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/opt/iobroker/node_modules/express/lib/router/index.js:346:12)
`

Versions:
ioBroker.webui: v0.11.0
ioBroker.admin: v6.10.1
ioBroker.docker: v8.1.0
Node.js: v18.17.1
NPM: 9.6.7

**Comment by ice987987** [comment]
ioBroker.web was installed and everything is working.
