### ISSUE TITLE
Events - Javascript funktioniert nicht mehr

### ISSUE THREAD

**Issue by Blockmove** [iobroker-community-adapters/ioBroker.webui#271]
In der Runtime kommt beim Ausführen folgende Fehlermeldung:
`Uncaught SyntaxError: Identifier 'importMapWidgets' has already been declared (at importmap.js:1:1)
:8082/favicon.ico:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
IobrokerHandler.js:96 ioBroker handler ready.
:8082/dist/frontend/common/IobrokerHandler.js:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
es-module-shims.js:743 Uncaught (in promise) TypeError: 404 Not Found http://ctrl01.fritz.box:8082/dist/frontend/common/IobrokerHandler.js
    at doFetch (es-module-shims.js:743:21)
    at async fetchModule (es-module-shims.js:751:17)
    at async es-module-shims.js:823:40
    at async loadAll (es-module-shims.js:469:5)
    at async topLevelLoad (es-module-shims.js:541:5)
    at async checkHash (runtime.html:73:17)
ScriptSystem.js:184 error parsing javascript TypeError: Failed to resolve module specifier "/webui/dist/frontend/common/IobrokerHandler.js". Invalid relative url or base scheme isn't hierarchical.
    at resolveIfNotPlainOrUrl (es-module-shims.js:130:15)
    at resolve (es-module-shims.js:410:38)
    at es-module-shims.js:848:32
    at Array.map (<anonymous>)
    at es-module-shims.js:844:45
    at async loadAll (es-module-shims.js:469:5)
    at async topLevelLoad (es-module-shims.js:541:5)
    at async ScriptSystem.assignAllScripts (ScriptSystem.js:178:28)
    at async HTMLElement.loadScreenData (ScreenViewer.js:88:30)
assignAllScripts @ ScriptSystem.js:184`

**Comment by jogibear9988** [comment]
fixed
